name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: cmtr-a9mdgrbi-bucket-1751148376
          AWS_ACCESS_KEY_ID: AKIA2Y6WD4HZBDC62EP5
          AWS_SECRET_ACCESS_KEY: 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
          AWS_REGION: us-east-1
